[package]
name = "fftbenchmark"
version = "0.1.0"
authors = ["Zsolt Kr√ºpl <hg2ecz@ham.hu>"]
edition = "2021"

[dependencies]

[lib]
name = "fft"
path = "src/fft.rs"
crate-type = ["rlib"]

[profile.release]
strip = true
